### PR TITLE
Create azure-pipelines.yml

### PR DESCRIPTION
**Pull request by WuShuning**
新增流水线定义文件

## Purpose

* ...

## Does this introduce a breaking change?

```
[ ] Yes
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Comment by WuShuning** [comment]
terst

**Comment by WuShuning** [comment]
pass

**Comment by diberry** [comment]
@WuShuning This pr appears to be missing files. Did you mean to create this PR or is there an update for the test file?

**Comment by diberry** [comment]
Closing for now. Feel free to reopen with more information.

**Pull request closed without merging**
