### PR TITLE
Added Moon Sun and Weather API access

### PR DESCRIPTION
**Pull request by PaytonADugas**
## Purpose

* ...

## Does this introduce a breaking change?

```
[ ] Yes
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Comment by PaytonADugas** [comment]
Added Moon sun and weather API

**Comment by PaytonADugas** [comment]
Added Moon Sun and Weather API

**Comment by PaytonADugas** [comment]
JUST MERGE!!!!!

**Comment by diberry** [comment]
Hi @PaytonADugas Did you mean to create this PR? Perhaps you wanted the PR on your own express project?

**Comment by PaytonADugas** [comment]
I am not sure what this is about...  I don't recall creating a PR with
Godaddy maybe?

**Pull request closed without merging**
